# Linear algebra

In [1]:
import numpy as np

In [12]:
a = np.array([[1.0, 2.0], [3.0, 4.0]], dtype="float32")
b = np.linalg.inv(a)
c=a @ b
print(c)

[[1. 0.]
 [0. 1.]]


In [14]:
%whos

Variable   Type       Data/Info
-------------------------------
a          ndarray    2x2: 4 elems, type `float32`, 16 bytes
b          ndarray    2x2: 4 elems, type `float32`, 16 bytes
c          ndarray    2x2: 4 elems, type `float32`, 16 bytes
np         module     <module 'numpy' from 'C:\<...>ges\\numpy\\__init__.py'>
v          ndarray    2: 2 elems, type `float32`, 8 bytes


In [15]:
v=np.linalg.eigvals(a)
V=np.linalg.eig(a)
print(v)
print(V)

[-0.3722813  5.3722816]
(array([-0.3722813,  5.3722816], dtype=float32), array([[-0.8245648 , -0.41597354],
       [ 0.56576747, -0.9093767 ]], dtype=float32))


In [23]:
V

(array([-0.3722813,  5.3722816], dtype=float32),
 array([[-0.8245648 , -0.41597354],
        [ 0.56576747, -0.9093767 ]], dtype=float32))