# Numpy Indexing, Slicing and Iterating

In [1]:
import numpy as np

In [2]:
NR=18
NC=17
a = np.arange(NR)**3
A=a
B=a[2]
C=a[0:2]
print("A={} \n\n B={} \n\n C={} \n\n".format(A,B,C))

A=[   0    1    8   27   64  125  216  343  512  729 1000 1331 1728 2197
 2744 3375 4096 4913] 

 B=8 

 C=[0 1] 




In [3]:
A=a[ : :-1]
B=a
B[0:6:2]=10000
C=a[0:2]
print("A={} \n\n B={} \n\n C={} \n\n".format(A,B,C))

A=[ 4913  4096  3375  2744  2197  1728  1331  1000   729   512   343   216
   125 10000    27 10000     1 10000] 

 B=[10000     1 10000    27 10000   125   216   343   512   729  1000  1331
  1728  2197  2744  3375  4096  4913] 

 C=[10000     1] 




In [4]:
def f(x,y):
    return 10*x+y

b = np.fromfunction(f,(5,4),dtype=int)

In [5]:
A=b
B=b[ : ,1]
C=b[2, : ]
print("A={} \n\n B={} \n\n C={} \n\n".format(A,B,C))

A=[[ 0  1  2  3]
 [10 11 12 13]
 [20 21 22 23]
 [30 31 32 33]
 [40 41 42 43]] 

 B=[ 1 11 21 31 41] 

 C=[20 21 22 23] 




Nos hemos quedado en https://numpy.org/devdocs/user/quickstart.html, Multidimensional arrays can have one index per axis. These indices are given in a tuple separated by commas

In [9]:
A=b
B=b[-1]
C=b[2:3, : ]
print("A={} \n\n B={} \n\n C={} \n\n".format(A,B,C))

A=[[ 0  1  2  3]
 [10 11 12 13]
 [20 21 22 23]
 [30 31 32 33]
 [40 41 42 43]] 

 B=[40 41 42 43] 

 C=[[20 21 22 23]] 




In [10]:
c = np.array( [[[  0,  1,  2],               # a 3D array (two stacked 2D arrays)
                [ 10, 12, 13]],
               [[100,101,102],
                [110,112,113]]])

In [11]:
c.shape

(2, 2, 3)

In [14]:
A=c[:, 0, :]
B=c[:,1 , :]
C=c
print("A={} \n\n B={} \n\n C={} \n\n".format(A,B,C))

A=[[  0   1   2]
 [100 101 102]] 

 B=[[ 10  12  13]
 [110 112 113]] 

 C=[[[  0   1   2]
  [ 10  12  13]]

 [[100 101 102]
  [110 112 113]]] 




In [16]:
for row in b:
    print(row)

[0 1 2 3]
[10 11 12 13]
[20 21 22 23]
[30 31 32 33]
[40 41 42 43]
