# Numpy Basics

In [1]:
import numpy as np

In [2]:
# b es un array y se pueden cambiar los elementos
b = np.array([(1.5,2,3), (4,5,6)], dtype=complex)
print(b)

[[1.5+0.j 2. +0.j 3. +0.j]
 [4. +0.j 5. +0.j 6. +0.j]]


In [3]:
# S es una tuple, es inmutable
S=b.shape
NR=S[0]
NC=S[1]
print(NR, NC)

2 3


In [4]:
# zero-offset
print(b[0,0], b[NR-1, NC-1])

(1.5+0j) (6+0j)


In [5]:
# tipos enteros
c=np.ones( S, dtype=np.int16 )  
print(c.dtype)

int16


In [6]:
z=b + c
print(z)

[[2.5+0.j 3. +0.j 4. +0.j]
 [5. +0.j 6. +0.j 7. +0.j]]


In [7]:
r=np.arange(0, NR)
r.shape=(NR,1)
print(r)

[[0]
 [1]]


In [8]:
c=2*np.pi*np.arange(2*NC)/NC
print(c)

[ 0.          2.0943951   4.1887902   6.28318531  8.37758041 10.47197551]


In [9]:
f=np.sin(c)
print(f)

[ 0.00000000e+00  8.66025404e-01 -8.66025404e-01 -2.44929360e-16
  8.66025404e-01 -8.66025404e-01]


In [10]:
print(np.power(f, 2))

[0.00000000e+00 7.50000000e-01 7.50000000e-01 5.99903913e-32
 7.50000000e-01 7.50000000e-01]


### en numpy no hay vectores hasta que se lo dices

In [11]:
r=np.arange(NR)
r.shape=(NR,1)
c=np.arange(NC)
c.shape=(NC,1)
A=r*r+3
B=r.dot(r.transpose())
C=r@c.transpose()
print("A={} \n B={} \n C={} \n".format(A,B,C))

A=[[3]
 [4]] 
 B=[[0 0]
 [0 1]] 
 C=[[0 0 0]
 [0 1 2]] 



In [17]:
NR=4
NC=3
a = np.ones((NR,NC), dtype=int)
b = np.random.random((NR,NC))
A=a
A*=3
B=b
B+=b
C=A+B
print("A={} \n\n B={} \n\n C={} \n\n".format(A,B,C))

A=[[3 3 3]
 [3 3 3]
 [3 3 3]
 [3 3 3]] 

 B=[[1.15659863 1.58531255 0.28585873]
 [1.87011257 1.49905499 1.94737487]
 [0.1584789  1.75527358 1.97538173]
 [0.00267155 0.40419633 1.93223128]] 

 C=[[4.15659863 4.58531255 3.28585873]
 [4.87011257 4.49905499 4.94737487]
 [3.1584789  4.75527358 4.97538173]
 [3.00267155 3.40419633 4.93223128]] 




In [18]:
# X are columns and Y are rows
X=0
Y=1
A=a.sum(axis=X)
B=b.mean(axis=Y)
C=b.mean()
print("A={} \n\n B={} \n\n C={} \n\n".format(A,B,C))


A=[12 12 12] 

 B=[1.00925664 1.77218081 1.29637807 0.77969972] 

 C=1.2143788087732494 


